apiVersion: v1
kind: ConfigMap
metadata:
  name: grocery-items-management-configmap
  namespace: lsefiane-dev
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATA_MONGODB_DATABASE: grocery-items
  SPRING_DATA_MONGODB_URI: mongodb+srv://lsefiane:dU3YEaWSQ9nfxBLI@cluster0.jk7ny7n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  SPRING_CACHE_TYPE: redis
  SPRING_REDIS_DATABASE: grocery-items
  SPRING_CACHE_REDIS_USERNAME: default
  SPRING_DATA_REDIS_DATABASE: '0'
  SPRING_DATA_REDIS_HOST: redis-11054.c91.us-east-1-3.ec2.cloud.redislabs.com
  SPRING_DATA_REDIS_PORT: '11054'
  SPRING_DATA_REDIS_TIMEOUT: '60000'
  MANAGEMENT_TRACING_ENABLED: "true"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: '1.0'
  SPRING_CLOUD_GATEWAY_ROUTES_0_ID: grocery-items-management
  SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://grocery-items-management:8080
  SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/groceryitem/api/**
  SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_1: Method=GET,POST,PUT,DELETE
  SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0_NAME: RequestRateLimiter
  SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0_ARGS_REDIS_RATE_LIMITER_REPLENISHRATE: '10'
  SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0_ARGS_REDIS_RATE_LIMITER_BURSTCAPACITY: '20'
  SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0_ARGS_REDIS_RATE_LIMITER_REQUESTEDTOKENS: '1'
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: TRACE
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: TRACE
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA: TRACE
immutable: true