services:
  grocery-items-management:
    image: lsefiane/grocery-items-management:latest
    container_name: grocery-items-management
    restart: unless-stopped
    pull_policy: always
    read_only: false
    expose:
      - ${GROCERY_ITEMS_MANAGEMENT_PORT}
    depends_on:
      - consul-server
      - redis
      - zipkin
    networks:
      - grocery-items-management-application
    environment:
      # Active Profile
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      # Application
      SPRING_APPLICATION_NAME: ${GROCERY_ITEMS_MANAGEMENT}
      SERVER_SERVLET_CONTEXT_PATH: ${SERVER_SERVLET_CONTEXT_PATH}
      # Spring Data MongoDB
      SPRING_DATA_MONGODB_DATABASE: ${SPRING_DATA_MONGODB_DATABASE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      # Spring Data Redis
      SPRING_DATA_REDIS_REPOSITORIES_ENABLED: ${SPRING_DATA_REDIS_REPOSITORIES_ENABLED}
      SPRING_CACHE_TYPE: ${SPRING_CACHE_TYPE}
      SPRING_CACHE_REDIS_USERNAME: ${SPRING_CACHE_REDIS_USERNAME}
      SPRING_REDIS_DATABASE: ${SPRING_REDIS_DATABASE}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}
      SPRING_DATA_REDIS_TIMEOUT: ${SPRING_DATA_REDIS_TIMEOUT}
      # Spring Cloud Consul
      SPRING_CLOUD_CONSUL_ENABLED: ${SPRING_CLOUD_CONSUL_ENABLED}
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CLOUD_CONSUL_HOST}
      SPRING_CLOUD_CONSUL_PORT: ${SPRING_CLOUD_CONSUL_PORT}
      SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKPATH: ${SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKPATH}
      # Zipkin
      MANAGEMENT_TRACING_ENABLED: ${MANAGEMENT_TRACING_ENABLED}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT}
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY}
      # Actuator
      MANAGEMENT_HEALTH_REDIS_ENABLED: ${MANAGEMENT_HEALTH_REDIS_ENABLED}
      MANAGEMENT_HEALTH_MONGODB_ENABLED: ${MANAGEMENT_HEALTH_MONGODB_ENABLED}
      # Logging
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA}
      # OpenApi / Swagger
      APPLICATION_NAME: ${APPLICATION_NAME}
      APPLICATION_DESCRIPTION: ${APPLICATION_DESCRIPTION}
      APPLICATION_VERSION: ${APPLICATION_VERSION}

networks:
  grocery-items-management-application: