services:

  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: unless-stopped
    pull_policy: always
    read_only: false
    command: ${CONSUL_SERVER_COMMAND}
    volumes:
      - ../hashicorp-consul/server.json:/consul/config/server.json:ro
    ports:
      - ${CONSUL_HTTP_HOST_PORT}:8500
      - ${CONSUL_UDP_HOST_PORT}:8600/udp
      - ${CONSUL_TCP_HOST_PORT}:8600/tcp
    networks:
      - grocery-items-management-application

  consul-client:
    image: hashicorp/consul:latest
    container_name: consul-client
    restart: unless-stopped
    command: ${CONSUL_CLIENT_COMMAND}
    volumes:
      - ../hashicorp-consul/client.json:/consul/config/client.json:ro
    depends_on:
      - consul-server
    networks:
      - grocery-items-management-application

networks:
  grocery-items-management-application: