services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    restart: unless-stopped
    pull_policy: always
    read_only: false
    ports:
      - ${ZIPKIN_PORT}:${ZIPKIN_PORT}
    networks:
      - grocery-items-management-application

networks:
  grocery-items-management-application: